### ISSUE TITLE
Non async version

### ISSUE THREAD

**Issue by paulsUsername** [typesense/typesense-swift#15]
## Description

My app supports back to iOS 11 so I am not using async-await yet. Is it possible to use this package without async await?

**Comment by DominiCanes** [comment]
I have the exact same question

**Comment by programVeins** [comment]
Hey @paulsUsername, @DominiCanes  👋🏽 at the moment, typesense-swift only supports iOS 13 and above with swift modern concurrency, so there is technically no way to use this package without async-await 😢 We might bring callback oriented architecture to the framework but not in the near-future.

You can checkout the [Typesense Documentation](https://typesense.org/docs/) for more information on how Typesense generally works.
