### ISSUE TITLE
StringQuantum Conversion

### ISSUE THREAD

**Issue by DominiCanes** [typesense/typesense-swift#16]
How do I actually convert the StringQuantum to a [String] and access each word in there? 
For example I have: 
hits![indexPath.row].highlights![0].matchedTokens!
Yet I am stuck with the StringQuantum data type and have no idea how to convert it to an array of Strings.

**Comment by programVeins** [comment]
Hey! I didn't realise I had missed this part earlier! Just wrote a small patch to get back your value of `MatchedTokens` from the `StringQuantum`

You can extract them from your StringQuantum type with `.arrStr` if it's an array of strings and `.arrArrStr` if it's an array of array of strings. Both of them return an optional and both cannot have values at the same time - it's only either one that you would want.

Fixed this in #17 Will be dropping a release soon 😁

**Comment by DominiCanes** [comment]
Thank you so much!
