### ISSUE TITLE
group_limit and page search parameters not give output 

### ISSUE THREAD

**Issue by NikunjChaudhari** [typesense/typesense-swift#41]
## Description

Unable to use page , groupLimit etc as they asked int type in searchparameter but in response getting errors like 
"Parameter `group_limit' must be an unsigned integer."

## Steps to reproduce

add searchParameters with page: 1 and grouplimit: 1 

<img width="884" alt="Screenshot 2024-11-05 at 10 19 37 AM" src="https://github.com/user-attachments/assets/e3be87df-aa57-43a1-b298-b8521e52c037">

## Expected Behavior

it should give response based on page and group_limit screenshot added below

<img width="1006" alt="Screenshot 2024-11-05 at 10 36 21 AM" src="https://github.com/user-attachments/assets/4efa9ea7-a829-47ed-baa7-18454cec317c">

## Actual Behavior

<img width="1009" alt="Screenshot 2024-11-05 at 10 26 48 AM" src="https://github.com/user-attachments/assets/f413a6e1-ab9f-4443-9109-8aa204a8f007">

here in SearchParameters i added page: 1, groupLimit: 1 while generate search parameter like this

let searchParameters = SearchParameters(q: parameters.q, queryBy: "productName,brandTitle,categoryList.categoryName,colourName", sortBy: "availableQuantity:desc,_text_match:desc,popularScore:desc", page: 1, perPage: 10, groupBy: "parentProductId", groupLimit: 1, excludeFields: "embedding,product_name_vector,detailDescription_vector,searchAbleAttributes,detailDescription,images.extraLarge,images.large,images.small")

but while api call curl generate and it become true value for page and group_limit  and give error like
{
    "message": "Parameter `group_limit` must be an unsigned integer."
}

and

{
    "message": "Parameter `page` must be an unsigned integer."
}

## Metadata

**Typesense Version**:
1.0.0

**OS**:
iOS Version 18.0.1

**Comment by NikunjChaudhari** [comment]
@phiHero  getting this error from logger

Request 1730814934820: Request to https://xrvu2bd0fjqz3y8ep-1.a1.typesense.net:443/collections/staging_sold_products/documents/search?per_page=30&page=true&query_by=productName,brandTitle,categoryList.categoryName,colourName&group_limit=30&sort_by=availableQuantity:desc,_text_match:desc,popularScore:desc&exclude_fields=embedding,product_name_vector,detailDescription_vector,searchAbleAttributes,detailDescription,images.extraLarge,images.large,images.small&q=Men&group_by=parentProductId was made. Response Code was 400
Error searching products: clientError(code: 400, desc: "Request failed with HTTP code 400 | Server said: Parameter `page` must be an unsigned integer.")

for request i am passing page:1  and groupLimit: 30 which you can refer from below attachment

<img width="854" alt="Screenshot 2024-11-05 at 7 27 46 PM" src="https://github.com/user-attachments/assets/df9ab426-bb9e-426c-bf35-3fefece20e23">

**Comment by phiHero** [comment]
@NikunjChaudhari  Does this also happen when you set the value to an integer other than 1? I'm thinking if the number 1 is being converted to `true` and 0 converted to `false`.

**Comment by phiHero** [comment]
OK found the bug! Fix should be right away

**Comment by phiHero** [comment]
@NikunjChaudhari could verify with v1.0.0-rc.1?

**Comment by NikunjChaudhari** [comment]
@phiHero yes i verified its working fine here are success logs

Request 1730867388631: Request to https://xrvu2bd0fjqz3y8ep-1.a1.typesense.net:443/collections/staging_sold_products/documents/search?exclude_fields=embedding,product_name_vector,detailDescription_vector,searchAbleAttributes,detailDescription,images.extraLarge,images.large,images.small&sort_by=availableQuantity:desc,_text_match:desc,popularScore:desc&group_limit=1&page=1&query_by=productName,brandTitle,categoryList.categoryName,colourName&group_by=parentProductId&q=Men&per_page=30 was made. Response Code was 200

@phiHero thank you for quick response and resolved it
